"""Curated content library + dialect metadata for the AI Content Creator Hub."""

DIALECTS = [
    {"code": "ar-EG", "name_en": "Egyptian Arabic", "name_native": "العامية المصرية"},
    {"code": "ar-LEV", "name_en": "Levantine Arabic", "name_native": "الشامية"},
    {"code": "ar-GULF", "name_en": "Gulf / Saudi Arabic", "name_native": "الخليجية"},
    {"code": "ar-IRQ", "name_en": "Iraqi Arabic", "name_native": "العراقية"},
    {"code": "ar-MAG", "name_en": "Maghrebi Darija", "name_native": "الدارجة المغربية"},
    {"code": "ku-BAD", "name_en": "Badini Kurdish", "name_native": "کوردی بادینی"},
]

CATEGORIES = ["tiktok-scripts", "ai-prompts", "content-ideas"]

SEED_CONTENT = [
    # ---------------- TikTok Scripts ----------------
    {
        "id": "tk-eg-1",
        "category": "tiktok-scripts",
        "dialect": "ar-EG",
        "title": "Morning Routine Hook",
        "title_native": "سكريبت روتين الصباح",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1758272421578-840698d05a00?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["روتين", "لايف ستايل", "هوك"],
        "body": "🎬 الهوك (أول 3 ثواني): «بطّل تصحّى الساعة 9 وانت زهقان! جرّب الحاجة دي 30 يوم وهتشكرني.»\n\n📌 المتن: «أول حاجة بعملها اني بشرب كباية ميه دافية.. بعدها 10 دقايق موبايل بعيد خالص. صدّقني دماغك هتصفى والانتاجية هتزيد.»\n\n📣 الدعوة للتفاعل: «اعمل سيف للفيديو ده وقول لي في الكومنت هتبدأ امتى؟»",
    },
    {
        "id": "tk-eg-2",
        "category": "tiktok-scripts",
        "dialect": "ar-EG",
        "title": "Product Review Skit",
        "title_native": "سكريبت ريفيو منتج",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1620755901999-166c6c151efe?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["ريفيو", "تسويق", "كوميدي"],
        "body": "🎬 الهوك: «اشتريت المنتج ده عشانكم.. وهقولكم بصراحة يستاهل ولا لأ.»\n\n📌 المتن: «التغليف تحفة، الخامة قوية، بس السعر شوية عالي. لو بتدوّر على جودة تعالى.. لو بتدوّر على رخص سيبه.»\n\n📣 الدعوة للتفاعل: «تحب أعمل ريفيو لإيه بعد كده؟ اكتبلي.»",
    },
    {
        "id": "tk-lev-1",
        "category": "tiktok-scripts",
        "dialect": "ar-LEV",
        "title": "Storytime Hook",
        "title_native": "سكريبت قصة قصيرة",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1758273705996-bdeefbdbce5e?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["ستوري تايم", "تشويق"],
        "body": "🎬 الهوك: «صار معي شغلة ما رح تصدّقوها.. خليكن معي لآخر الفيديو.»\n\n📌 المتن: «كنت رايح عالشغل عادي، وفجأة لقيت ظرف عالأرض فيه ورقة مكتوب عليها اسمي! تخيّلوا كيف صرت.»\n\n📣 الدعوة للتفاعل: «شو بتوقّعوا كان جوا الظرف؟ جاوبوني بالكومنت.»",
    },
    {
        "id": "tk-gulf-1",
        "category": "tiktok-scripts",
        "dialect": "ar-GULF",
        "title": "Motivation Reel",
        "title_native": "سكريبت تحفيزي",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["تحفيز", "نجاح"],
        "body": "🎬 الهوك: «لا تنتظر الظروف تصير مثالية.. ابدأ وانت خايف.»\n\n📌 المتن: «كل شخص ناجح تشوفه اليوم بدأ وهو ما يدري وش يسوي. الفرق إنه ما وقف. اشتغل بصمت وخل نجاحك يسولف.»\n\n📣 الدعوة للتفاعل: «احفظ المقطع وارجع له لمن تحس إنك تبي تستسلم.»",
    },
    {
        "id": "tk-irq-1",
        "category": "tiktok-scripts",
        "dialect": "ar-IRQ",
        "title": "Food Recipe Hook",
        "title_native": "سكريبت وصفة اكل",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["طبخ", "وصفات"],
        "body": "🎬 الهوك: «اكلة تسوّيها بـ 5 دقايق وتنبسط عليها العائلة كلها.»\n\n📌 المتن: «نجيب بيضتين، شوية جبن، وخبز صمون.. نخلطهم ونحطهم بالمقلاة. صدكني يطلع طعم خرافي.»\n\n📣 الدعوة للتفاعل: «جرّبوها وكَلّولي شلون طلعت وياكم.»",
    },
    {
        "id": "tk-ku-sor-1",
        "category": "tiktok-scripts",
        "dialect": "ku-BAD",
        "title": "Daily Vlog Hook",
        "title_native": "سکریپتی ڤلۆگی ڕۆژانە",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1630797160666-38e8c5ba44c1?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["ڤلۆگ", "ژیان"],
        "body": "🎬 هوک: «ئەم شتە بکە بۆ ماوەی ٧ ڕۆژ، دڵنیام ژیانت دەگۆڕێت.»\n\n📌 ناوەڕۆک: «هەموو بەیانییەک پێش ئەوەی مۆبایل بکەیتەوە، ١٠ خولەک بۆ خۆت تەرخان بکە. بیر لە ئامانجەکانت بکەرەوە و بەرنامەی ڕۆژەکەت دابنێ.»\n\n📣 بانگەواز: «ڤیدیۆکە سەیڤ بکە و لە کۆمێنت بڵێ کەی دەستپێدەکەیت.»",
    },
    {
        "id": "tk-ku-bad-1",
        "category": "tiktok-scripts",
        "dialect": "ku-BAD",
        "title": "Comedy Skit",
        "title_native": "سکریپتا کۆمیدی",
        "badge": "Viral Ready",
        "preview_image_url": "https://images.unsplash.com/photo-1582298538104-fe2e74c27f59?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["کۆمیدی", "پێکەنین"],
        "body": "🎬 هوک: «دەمێ دایکا من گازی من دکەت بۆ خوارنێ...»\n\n📌 ناڤەرۆک: «ئەز ژ ژوورا خۆ دەرکەڤم، لێ بەری هەمی تشتی دبێژم چ چێکری؟ پاشی دبینم هەمی مالبات ل بەنداڤا منن.»\n\n📣 بانگەهیشتن: «ئەگەر ئەڤە ب سەرێ هەوە هاتیە، کۆمێنتێ بکەن.»",
    },
    # ---------------- AI Image Prompts ----------------
    {
        "id": "ai-1",
        "category": "ai-prompts",
        "dialect": "ar-GULF",
        "title": "Cinematic Desert Portrait",
        "title_native": "بورتريه صحراوي سينمائي",
        "badge": "Midjourney & Flux",
        "preview_image_url": "https://images.unsplash.com/photo-1682199040197-23d5c7bc3f55?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["portrait", "cinematic", "desert"],
        "body": "Cinematic portrait of a young Gulf Arab man wearing a crisp white thobe and ghutra, standing in golden desert dunes at sunset, warm rim lighting, shallow depth of field, ultra-realistic skin texture, shot on 85mm lens, film grain, --ar 9:16 --style raw --v 6",
    },
    {
        "id": "ai-2",
        "category": "ai-prompts",
        "dialect": "ar-EG",
        "title": "Old Cairo Street Scene",
        "title_native": "مشهد شارع القاهرة القديمة",
        "badge": "Midjourney & Flux",
        "preview_image_url": "https://images.unsplash.com/photo-1710211288826-b7df3ab71588?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["street", "vintage", "cairo"],
        "body": "A bustling old Cairo alley at golden hour, hanging fanoos lanterns, worn sandstone walls, a woman in colorful galabeya selling spices, warm cinematic lighting, hyper-detailed, photorealistic, atmospheric haze, 35mm street photography --ar 4:5 --v 6",
    },
    {
        "id": "ai-3",
        "category": "ai-prompts",
        "dialect": "ku-BAD",
        "title": "Kurdish Mountain Heritage",
        "title_native": "میراتی چیای کوردی",
        "badge": "Midjourney & Flux",
        "preview_image_url": "https://images.unsplash.com/photo-1621425022462-a14e58eebcc0?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["heritage", "mountains", "kurdish"],
        "body": "A proud Kurdish woman in traditional embroidered kras u fistan dress standing on a green Zagros mountain terrace, snow peaks behind, soft morning fog, vibrant fabric colors, national geographic style, ultra-detailed, natural light --ar 3:4 --style raw --v 6",
    },
    {
        "id": "ai-4",
        "category": "ai-prompts",
        "dialect": "ar-LEV",
        "title": "Levantine Food Flatlay",
        "title_native": "تصوير طعام شامي",
        "badge": "Midjourney & Flux",
        "preview_image_url": "https://images.unsplash.com/photo-1697126248475-a537cc5cce28?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["food", "flatlay", "product"],
        "body": "Top-down flatlay of a Levantine mezze spread: hummus, tabbouleh, fresh pita, olives, and mint tea on a rustic wooden table, soft daylight from the side, appetizing steam, food photography, high detail, moody warm tones --ar 1:1 --v 6",
    },
    {
        "id": "ai-5",
        "category": "ai-prompts",
        "dialect": "ar-IRQ",
        "title": "Neon Baghdad Nights",
        "title_native": "بغداد الليلية بالنيون",
        "badge": "Midjourney & Flux",
        "preview_image_url": "https://images.unsplash.com/photo-1672872476232-da16b45c9001?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["neon", "cyberpunk", "city"],
        "body": "Futuristic cyberpunk vision of Baghdad at night, neon signs in Arabic calligraphy, rain-slicked streets reflecting cyan and magenta light, a lone figure with an umbrella, blade-runner aesthetic, volumetric fog, ultra-detailed, 8k --ar 16:9 --v 6",
    },
    # ---------------- Content Ideas ----------------
    {
        "id": "ci-eg-1",
        "category": "content-ideas",
        "dialect": "ar-EG",
        "title": "10 Viral Content Angles",
        "title_native": "10 أفكار محتوى فيرال",
        "badge": "Trending Concepts",
        "preview_image_url": "https://images.unsplash.com/photo-1620396748669-46bd3128ccce?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["أفكار", "ترند"],
        "body": "1. «يوم في حياتي» بس بطريقة كوميدية.\n2. رياكشن على ترند قديم رجع تاني.\n3. قبل وبعد لتحدي معين.\n4. أسرار مجال شغلك في 30 ثانية.\n5. الرد على أكتر سؤال بيتكرر.\n6. تحدي 7 أيام قدام الكاميرا.\n7. أغلط 3 أخطاء بيقع فيها المبتدئين.\n8. مقارنة منتجين بسعرين.\n9. ستوري تايم من طفولتك.\n10. سؤال للجمهور يخلّيهم يتفاعلوا.",
    },
    {
        "id": "ci-gulf-1",
        "category": "content-ideas",
        "dialect": "ar-GULF",
        "title": "Business Content Series",
        "title_native": "سلسلة محتوى بزنس",
        "badge": "Trending Concepts",
        "preview_image_url": "https://images.unsplash.com/photo-1499914485622-a88fac536970?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["بزنس", "سلسلة"],
        "body": "1. كيف بدأت مشروعك من الصفر.\n2. أكبر خطأ كلّفك فلوس.\n3. أدوات تستخدمها كل يوم.\n4. نصيحة لو رجعت بالوقت.\n5. جولة في مكان شغلك.\n6. رد على تعليقات المتابعين.\n7. تحدّي: مشروع بـ 100 ريال.",
    },
    {
        "id": "ci-ku-sor-1",
        "category": "content-ideas",
        "dialect": "ku-BAD",
        "title": "Educational Reel Ideas",
        "title_native": "بیرۆکەی ناوەڕۆکی فێرکاری",
        "badge": "Trending Concepts",
        "preview_image_url": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["فێرکاری", "بیرۆکە"],
        "body": "١. لە ٦٠ چرکەدا شتێکی نوێ فێری خەڵک بکە.\n٢. هەڵەی باو لە بوارەکەت ڕوونبکەرەوە.\n٣. بەراوردی دوو شت بۆ بڕیاردان.\n٤. چیرۆکی سەرکەوتنێکی کەسی.\n٥. وەڵامی پرسیاری زۆر دووبارەبووەوە.\n٦. لیستی ٥ ئامرازی بەسوود.\n٧. ڕۆژێک لە ژیانی پیشەکەت.",
    },
    {
        "id": "ci-lev-1",
        "category": "content-ideas",
        "dialect": "ar-LEV",
        "title": "Lifestyle Vlog Ideas",
        "title_native": "أفكار فلوجات لايف ستايل",
        "badge": "Trending Concepts",
        "preview_image_url": "https://images.unsplash.com/photo-1673767298248-b128f17f89af?crop=entropy&cs=srgb&fm=jpg&q=80&w=800",
        "tags": ["فلوج", "لايف ستايل"],
        "body": "1. جولة الصبح بروتيني كامل.\n2. طبخة تقليدية من ستّي.\n3. تنظيم البيت بطريقة مريحة.\n4. يوم تسوّق بميزانية محدودة.\n5. عادات صغيرة غيّرت حياتي.\n6. رد على أسئلتكن الشخصية.\n7. تحدّي أسبوع بدون سوشال ميديا.",
    },
]

# ---------------- Expanded AI Image Prompt Library ----------------
def _p(url):
    return url if "?" in url else url + "?crop=entropy&cs=srgb&fm=jpg&q=80&w=800"

SEED_CONTENT += [
    {
        "id": "ai-6", "category": "ai-prompts", "dialect": "ku-BAD",
        "title": "Person in Lush Green Nature", "title_native": "کەسێک لە سروشتی سەوز",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1617634667039-8e4cb277ab46"),
        "tags": ["nature", "green", "portrait"],
        "body": "A young person standing on a rolling emerald hillside in the Kurdish highlands, wildflowers in the foreground, soft diffused overcast light, distant misty mountains, cinematic wide shot, natural earthy color palette, photorealistic, 35mm --ar 3:4 --style raw --v 6",
    },
    {
        "id": "ai-7", "category": "ai-prompts", "dialect": "ar-EG",
        "title": "Pyramids at Sunrise", "title_native": "الأهرامات عند الشروق",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1759212315137-9ad35784dffb"),
        "tags": ["egypt", "pyramids", "sunrise"],
        "body": "The Giza pyramids at golden sunrise, hot-air balloons drifting above the desert, long soft shadows on the sand, warm amber and rose sky, epic cinematic scale, ultra-detailed, aerial perspective, high dynamic range --ar 16:9 --v 6",
    },
    {
        "id": "ai-8", "category": "ai-prompts", "dialect": "ar-IRQ",
        "title": "Iraqi Golden Shrine", "title_native": "المرقد الذهبي العراقي",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1718680962024-0fa899e1815e"),
        "tags": ["iraq", "architecture", "golden"],
        "body": "A majestic golden-domed shrine in an Iraqi city at dusk, intricate turquoise tilework and minarets, warm sunset glow reflecting off the gold, bustling old town rooftops below, cinematic, ultra-detailed architecture, atmospheric haze --ar 4:5 --v 6",
    },
    {
        "id": "ai-9", "category": "ai-prompts", "dialect": "ar-IRQ",
        "title": "Iraqi Marshes Canoe", "title_native": "أهوار العراق",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1712264592134-3a79d580ad3a"),
        "tags": ["iraq", "marshes", "documentary"],
        "body": "A Marsh Arab paddling a slender mashoof canoe through the reed beds of the Mesopotamian marshes, golden hour reflections on calm water, traditional reed house in the background, documentary photography style, soft warm light, ultra-detailed --ar 3:2 --v 6",
    },
    {
        "id": "ai-10", "category": "ai-prompts", "dialect": "ar-GULF",
        "title": "Traditional Arabic Coffee", "title_native": "القهوة العربية الأصيلة",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1604924434662-4127d9fa3070"),
        "tags": ["coffee", "product", "culture"],
        "body": "A polished brass dallah coffee pot pouring Arabic qahwa into a small finjan cup, roasted coffee beans and dates scattered on a dark surface, dramatic side lighting, rising steam, moody product photography, macro detail, warm tones --ar 1:1 --v 6",
    },
    {
        "id": "ai-11", "category": "ai-prompts", "dialect": "ar-MAG",
        "title": "Chefchaouen Blue Alley", "title_native": "شفشاون الزرقاء",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1538600838042-6a0c694ffab5"),
        "tags": ["morocco", "blue", "street"],
        "body": "A narrow blue-washed staircase alley in Chefchaouen Morocco, hanging woven baskets and colorful textiles, potted plants, warm afternoon light spilling in, travel photography, vivid cobalt tones, ultra-detailed, 35mm --ar 4:5 --v 6",
    },
    {
        "id": "ai-12", "category": "ai-prompts", "dialect": "ar-LEV",
        "title": "Damascus Old Alley", "title_native": "أزقة دمشق القديمة",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1697200223163-03acafab8873"),
        "tags": ["damascus", "night", "street"],
        "body": "A quiet narrow alley in old Damascus at blue hour, a single warm lantern glowing at the far end, ancient stone walls and wooden shutters, moody cinematic lighting, atmospheric, deep shadows, photorealistic --ar 4:5 --v 6",
    },
    {
        "id": "ai-13", "category": "ai-prompts", "dialect": "ar-GULF",
        "title": "Dubai Skyline Storm", "title_native": "أفق دبي",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1651467606797-e1c660cf3fda"),
        "tags": ["dubai", "skyline", "cinematic"],
        "body": "The Dubai downtown skyline with the Burj Khalifa piercing dramatic storm clouds, moody cinematic lighting, city lights beginning to glow, ultra-wide architectural shot, high detail, teal and grey palette, 8k --ar 16:9 --v 6",
    },
    {
        "id": "ai-14", "category": "ai-prompts", "dialect": "ar-EG",
        "title": "Arabic Calligraphy Art", "title_native": "فن الخط العربي",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1646229227468-ba6eb534d368"),
        "tags": ["calligraphy", "art", "abstract"],
        "body": "Elegant flowing Arabic calligraphy in gold on a deep textured background, dramatic directional lighting casting soft shadows, fine art photography, luxurious and minimal, high contrast, ultra-detailed brush strokes --ar 1:1 --v 6",
    },
    {
        "id": "ai-15", "category": "ai-prompts", "dialect": "ar-GULF",
        "title": "Bedouin Desert Night", "title_native": "ليل البادية تحت النجوم",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1783696508616-f916440eca9d"),
        "tags": ["desert", "night", "stars"],
        "body": "A Bedouin desert camp beneath a breathtaking starry milky-way sky, glowing campfire illuminating sandstone rock formations, tents softly lit, long exposure astrophotography, deep blues and warm amber, ultra-detailed --ar 16:9 --v 6",
    },
    {
        "id": "ai-16", "category": "ai-prompts", "dialect": "ar-IRQ",
        "title": "Traditional Tea Setup", "title_native": "طقم الشاي التقليدي",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1623065492741-5cf3690b4535"),
        "tags": ["tea", "product", "culture"],
        "body": "An ornate Middle Eastern tea set on a patterned tablecloth, engraved brass pot and small glass istikan filled with amber tea, dates and sweets on a tray, warm cozy lighting, food photography, shallow depth of field, rich detail --ar 4:5 --v 6",
    },
    {
        "id": "ai-17", "category": "ai-prompts", "dialect": "ku-BAD",
        "title": "Kurdish Newroz Fire", "title_native": "ئاگری نەورۆز",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1569430251091-da3b108cff29"),
        "tags": ["newroz", "festival", "fire"],
        "body": "A towering Newroz bonfire at night with a crowd of people in colorful Kurdish dress celebrating around it, sparks flying into the dark sky, warm orange glow on faces, energetic festive atmosphere, cinematic, ultra-detailed --ar 3:2 --v 6",
    },
    {
        "id": "ai-18", "category": "ai-prompts", "dialect": "ar-GULF",
        "title": "Arabian Falcon Portrait", "title_native": "صقر عربي",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1694891886014-dd3e98315391"),
        "tags": ["falcon", "portrait", "wildlife"],
        "body": "An intense close-up portrait of a majestic falcon, razor-sharp eyes and detailed feathers, soft blurred desert background, dramatic natural light, wildlife photography, 200mm telephoto, hyper-detailed, shallow depth of field --ar 4:5 --v 6",
    },
    {
        "id": "ai-19", "category": "ai-prompts", "dialect": "ar-EG",
        "title": "Night Street Food Vendor", "title_native": "بائع أكل الشارع بالليل",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1558697049-a7c3a41d18f5"),
        "tags": ["street", "food", "night"],
        "body": "A lively Middle Eastern night market alley, glowing lanterns overhead, a street vendor grilling food with steam and smoke rising, warm bokeh lights, cinematic reportage photography, vibrant colors, ultra-detailed --ar 4:5 --v 6",
    },
    {
        "id": "ai-20", "category": "ai-prompts", "dialect": "ar-LEV",
        "title": "Cozy Reading Nook", "title_native": "ركن قراءة دافئ",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1547250936-e1426b362327"),
        "tags": ["cozy", "lifestyle", "warm"],
        "body": "A woman reading a book in a cozy sunlit attic nook, holding a warm cup, soft knit blankets and plants around, dreamy morning light through a skylight, warm inviting tones, lifestyle photography, shallow depth of field --ar 4:5 --v 6",
    },
    {
        "id": "ai-21", "category": "ai-prompts", "dialect": "ku-BAD",
        "title": "Kurdistan Valley Aerial", "title_native": "دیمەنی ئاسمانی دۆڵی کوردستان",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1501854140801-50d01698950b"),
        "tags": ["aerial", "landscape", "nature"],
        "body": "A sweeping aerial view of endless rolling green Kurdish mountain ridges, soft cloud shadows drifting across the valleys, morning haze, epic landscape photography, rich greens, ultra-detailed, drone perspective --ar 16:9 --v 6",
    },
    {
        "id": "ai-22", "category": "ai-prompts", "dialect": "ar-MAG",
        "title": "Moroccan Hillside Town", "title_native": "مدينة مغربية على التل",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1569383746724-6f1b882b8f46"),
        "tags": ["morocco", "town", "travel"],
        "body": "A picturesque Moroccan hillside town of blue and white houses cascading down a cliff, bright clear sky, distant sea, vibrant travel photography, crisp midday light, ultra-detailed, wide establishing shot --ar 16:9 --v 6",
    },
    {
        "id": "ai-23", "category": "ai-prompts", "dialect": "ar-GULF",
        "title": "Dubai Aerial Dusk", "title_native": "دبي من الأعلى وقت الغروب",
        "badge": "Midjourney & Flux",
        "preview_image_url": _p("https://images.unsplash.com/photo-1652707228067-25672fa0b082"),
        "tags": ["dubai", "aerial", "dusk"],
        "body": "A breathtaking aerial view of Dubai at dusk, glowing highways and skyscrapers, pink and orange sunset sky, light trails from traffic, cinematic long-exposure cityscape, ultra-detailed, high dynamic range --ar 16:9 --v 6",
    },
]

